apiVersion: 1

datasources:
  - name: gostrategy-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: gostrategy-prometheus
    isDefault: true

  - name: gostrategy-loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: gostrategy-loki
