apiVersion: 1

datasources:
  - name: gostrategy-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: gostrategy-prometheus
    isDefault: true

  - name: gostrategy-loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: gostrategy-loki

  - name: gostrategy-postgres
    type: postgres
    access: proxy
    url: 192.168.200.4:5432
    user: gostrategy
    database: gostrategy
    uid: gostrategy-postgres
    jsonData:
      sslmode: "disable"
      database: gostrategy
    secureJsonData:
      password: "pass"
